### ISSUE TITLE
Calculator Program not Working

### ISSUE THREAD

**Issue by HarshSharma00121** [HarshSharma00121/My-Awesome-Calculator#1]
Can i have an improved algorithm in my Code.

**Comment by codewith-arijit** [comment]
Have improved and edited your code. Check the PR and merge it. 
Regards.

**Comment by tausiq2003** [comment]
hello @HarshSharma00121 can i write a better code for this and can i do this for hacktoberfest2021

**Comment by tausiq2003** [comment]
Please reply
